samples:
    2015T: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/snakemake_Yomna/data/2015T/toxo.fastq
    2020T: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/snakemake_Yomna/data/2020T/toxo.fastq
    2000B: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/snakemake_Yomna/data/2000B/concat_filtered_Toxo2000B_6.fastq
models:
    2015T: r103_min_high_g345
    2020T: r103_hac_variant_g507
    2000B: r103_sup_variant_g507
conda_env:
    sniffles: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/ToxoVar/workflow/envs/sniffles_env.yaml
    GraphAligner: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/ToxoVar/workflow/envs/GraphAligner.yaml
Files:
    ref: /home/yomna/Desktop/PhD_Yomna_Gohar/fasta/ME49_genome_from_Third_generation_sequencing_paper/ToxoME49_GenBank_JACEHA000000000.1.fsa
    gff: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/Data/t-gondii-me49-new-genome-annotation_results/scaffold.out.modified.with.gffread.and.with.biotype.for.vep.gff3.gz
    agp: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/Data/t-gondii-me49-new-genome-annotation_results/pseudo.pseudochr.agp
pileup:
    2015T: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/Medaka/2020T/analysis_2020T_Genbank/pileup/ToxoME49_2020T_combined_reads_to_Genbank_mpileup.txt
    2020T: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/Medaka/2020T/analysis_2020T_Genbank/pileup/ToxoME49_2020T_combined_reads_to_Genbank_mpileup.txt
    2000B: /home/yomna/Desktop/PhD_Yomna_Gohar/graph_genome_project/Medaka/2000B/ToxoME49_2000B_combined_filtered_samples_using_finding_strain_script/medaka_2407/medakaGenbank/genbank_pileup/ToxoME49_2000B_combined_reads_to_Genbank__mpileup_2407.txt
tools:    
    snpEff_path: /home/yomna/Desktop/PhD_Yomna_Gohar/Softwares/snpEff_latest_core/snpEff/SnpSift.jar
    Ensemble_vep: /home/yomna/Desktop/PhD_Yomna_Gohar/Softwares/ensembl-vep/vep
    vg: /home/yomna/Desktop/PhD_Yomna_Gohar/Softwares/vg

#sniffles needs to be a seperate conda environment named sniffles (here old version from 2022):
#pybedtools needs to be installed (pip install pybedtools) for automatic filtering 
