samples:
    2015T: /home/marie/toxo_proj/data_Toxoproj/ToxoME49_2015T/concat_2015T/toxo.fastq
    2020T: /home/marie/toxo_proj/data_Toxoproj/ToxoME49_2020T/concat_2020T/toxo.fastq
    2000B: /home/marie/toxo_proj/data_Toxoproj/Toxo_Me49_2000B_data/concat_filtered_Toxo2000B_6.fastq
models:
    2015T: r103_min_high_g345
    2020T: r103_hac_variant_g507
    2000B: r103_sup_variant_g507
conda_env:
    sniffles: /home/marie/masterthesis/snakemake_Yomna_2/workflow/envs/sniffles_env.yaml
    GraphAligner: /home/marie/masterthesis/snakemake_Yomna_2/workflow/envs/GraphAligner.yaml
Files:
    ref: /home/marie/toxo_proj/data_Toxoproj/ref_genome/GenBank_ref_genome/ToxoME49_GenBank_JACEHA000000000.1.fsa
    gff: /home/marie/masterthesis/data/infile_vep/scaffold.out.modified.with.gffread.and.with.biotype.for.vep.gff3.gz
    agp: /home/marie/masterthesis/data/unplaced_seq/pseudo.pseudochr.agp
pileup:
    2015T: /home/marie/toxo_proj/data_Toxoproj/mpileup_ToxoME49_2015T/ToxoME49_2015T_combined_reads_to_Genbank_mpileup.txt
    2020T: /home/marie/toxo_proj/data_Toxoproj/mpileup_ToxoME49_2020T/ToxoME49_2020T_combined_reads_to_Genbank_mpileup.txt
    2000B: /home/marie/toxo_proj/data_Toxoproj/mpileup_Toxo2000B_2407/ToxoME49_2000B_combined_reads_to_Genbank__mpileup_2407.txt
tools:    
    snpEff_path: /home/marie/tools/snpEff/snpEff/SnpSift.jar
    Ensemble_vep: /home/marie/tools/vep/ensembl-vep/vep
    vg: /home/marie/tools/vg/bin/vg
    medaka_env: /home/marie/tools/medaka/medaka/venv/bin/activate
    
#sniffles needs to be a seperate conda environment named sniffles (here old version from 2022):
#pybedtools needs to be installed (pip install pybedtools) for automatic filtering 
